ALTER TABLE FarmerPhones 
	--ADD FOREIGN KEY (cc) REFERENCES LM_CC(cc);
	--DROP CONSTRAINT FK__Buys__cc__4A8310C6;
ALTER COLUMN phone CHAR(11) NOT NULL;
--ALTER TABLE LM_CC
	--ADD PRIMARY KEY (cc);
	--DROP CONSTRAINT PK__LM_CC__3213666DA4A7C9CB;
--ALTER COLUMN cc CHAR(16) NOT NULL;

--GO
--SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE