CREATE TABLE Deposits(
	deposit_id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	fid INT NOT NULL FOREIGN KEY REFERENCES Farmer(fid),
	rid INT NOT NULL FOREIGN KEY REFERENCES Website(rid),
	amount INT NOT NULL
)